import 'package:charity_life/enums/dependencies.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_EN': {
          'titleLogin': 'Welcome back',
          'descLogin':
              'Enter the email address associated with your CharityLife account',
          'email': 'Email address',
          'password': 'Password',
          'rememberMe': 'Remember password',
          'forgot': 'Forgot password?',
          'vTitle': '6-digit code',
          'vDesc': 'Please enter the code we’ve sent to your email address',
          'vBodyText': 'Didn’t get the code? Resend in 30:18',
          'nPasswordTitle': 'Set new password',
          'nPasswordDesc':
              'Enter a new and more secure password for your account',
          'nPassword': 'New password',
          'cPassword': 'Confirm password',
          'dTitle': 'Dashboard',
          'dHeading': 'Total Donations Amount',
          'dBtn': 'Allocate Donations',
          'dBalance': 'SAR 2,651.00 ',
          'dInventory': 'Inventory Levels',
          'dInventoryDesc': 'Product Categories',
          'dGraphF': 'Food',
          'dGraphB': 'Beverages',
          'dGraphC': 'Cleaning',
          'dGraphH': 'Hygiene',
          'dGraphG': 'Grains',
          'dManageOrder': 'Manage Pending Orders',
          'dManageOrderDesc':
              'You can see all pending orders here and assign & dispatch orders from here.',
          'dManageDonations': 'Manage Donations',
          'dManageDonationDesc':
              'You can see and post all the unposted donations from donors through here.',
          'dManageUserApprovel': 'Pending User Approvals',
          'dManageUserApprovelDesc':
              'You can approve or reject all new users signed up on the system through here.',
          'dPendingTitle': 'Pending Orders',
          'dTabAll': 'All',
          'dAssigned': 'Assigned',
          'dNotAssigned': 'Not assigned',
          'dDispatch': 'Dispatched',
          'dOrderId': 'Order ID',
          'dBeneficiary': 'Beneficiary',
          'dOrdertext': 'ORD-23505',
          'dStatus': '',
          'dDeliveryTitle': 'Select Delivery Volunteer',
          'dDeliveryDesc': 'Select delivery volunteer',
          'dDonationTitle': 'Donations',
          //----------------Beneficiary User-----------------//
          'bDashboardTilte': 'Good Morning',
          'bAccountBalanceTitle': 'Account Balance',
          'bAccountBalance': '',
          'bCategoryTitle': '',
          'bProductName': '',
          'bProductTitle': '',
          'bProductDesc': '',
          'bProductPrice': '',
          'bProductAvailabilty': '',
          'bProductStock': '',
          'bMyCartTitle': 'My Cart',
          'bCartProductName': '',
          'bCartProductDesc': '',
          'bCartProductSubtotal': '',
          'bCartProductUnit': '',
          'bCheckOutTitle': 'Checkout',
          'bCheckHeading': 'Your Details',
          'bCheckOutEmail': 'shahzaibamjad234@gmail.com',
        },
        'ar_AR': {
          'titleLogin': 'مرحبًا بعودتك',
          'descLogin':
              'أدخل عنوان البريد الإلكتروني المرتبط بحسابك حساب الحياة الخيرية',
          'email': 'عنوان البريد الإلكتروني',
          'password': 'كلمة المرور',
          'rememberMe': 'تذكرني',
          'forgot': 'نسيت كلمة المرور؟',
          'vTitle': 'رمز مكون من 6 أرقام',
          'vDesc': 'الرجاء إدخال الرمز الذي أرسلناه إلى عنوان بريدك الإلكتروني',
          'vBodyText': 'لم تحصل على الرمز؟ إعادة الإرسال في 01:30',
          'nPasswordTitle': 'تعيين كلمة مرور جديدة',
          'nPasswordDesc': 'أدخل كلمة مرور جديدة وأكثر أمانًا لحسابك',
          'nPassword': 'كلمة المرور الجديدة',
          'cPassword': 'تأكيد كلمة المرور',
          'dTitle': 'Dashboard',
          'dHeading': 'Total Donations Amount',
          'dBtn': 'Allocate Donations',
          'dBalance': 'SAR 2,651.00 ',
          'dInventory': 'Inventory Levels',
          'dInventoryDesc': 'Product Categories',
          'dGraphF': 'Food',
          'dGraphB': 'Beverages',
          'dGraphC': 'Cleaning',
          'dGraphH': 'Hygiene',
          'dGraphG': 'Grains',
          'dManageOrder': 'Manage Pending Orders',
          'dManageOrderDesc':
              'You can see all pending orders here and assign & dispatch orders from here.',
          'dManageDonations': 'Manage Donations',
          'dManageDonationDesc':
              'You can see and post all the unposted donations from donors through here.',
          'dManageUserApprovel': 'Pending User Approvals',
          'dManageUserApprovelDesc':
              'You can approve or reject all new users signed up on the system through here.',
          'dPendingTitle': 'Pending Orders',
          'dTabAll': 'All',
          'dAssigned': 'Assigned',
          'dNotAssigned': 'Not assigned',
          'dDispatch': 'Dispatched',
          'dOrderId': 'Order ID',
          'dBeneficiary': 'Beneficiary',
          'dOrdertext': 'ORD-23505',
          'dStatus': '',
          'dDeliveryTitle': 'Select Delivery Volunteer',
          'dDeliveryDesc': 'Select delivery volunteer',
          'dDonationTitle': 'Donations',
          //----------------Beneficiary User-----------------//
          'bDashboardTilte': 'Good Morning',
          'bAccountBalanceTitle': 'Account Balance',
          'bAccountBalance': '',
          'bCategoryTitle': '',
          'bProductName': '',
          'bProductTitle': '',
          'bProductDesc': '',
          'bProductPrice': '',
          'bProductAvailabilty': '',
          'bProductStock': '',
          'bMyCartTitle': 'My Cart',
          'bCartProductName': '',
          'bCartProductDesc': '',
          'bCartProductSubtotal': '',
          'bCartProductUnit': '',
          'bCheckOutTitle': 'Checkout',
          'bCheckHeading': 'Your Details',
          'bCheckOutEmail': 'shahzaibamjad234@gmail.com',
        },
      };
}
